name: Build APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      JAVA_HOME: /opt/hostedtoolcache/jdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Android command line tools and SDK packages
        run: |
          set -e
          SDK_ROOT="$ANDROID_SDK_ROOT"
          mkdir -p "$SDK_ROOT"
          cd "$SDK_ROOT"
          echo "Downloading Android command line tools..."
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools-temp
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/
          export PATH="$SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --sdk_root="$SDK_ROOT" --licenses || true
          sdkmanager --sdk_root="$SDK_ROOT" "platform-tools" "platforms;android-36" "build-tools;36.0.0" "ndk;27.1.12297006" "cmake;3.22.1" "cmdline-tools;latest"

      - name: Show SDK info
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          ls -la "$ANDROID_SDK_ROOT"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run prebuild and gradle fix
        run: npm run prebuild-android

      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug --no-daemon

      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: NeuroLearn-APKs
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/apk/release/app-release.apk
